#!/bin/bash
# GitHub Backup Manager - Quick Reference Card

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║          GitHub Backup Manager - Quick Reference                  ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

# Colors (for terminal output)
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}📁 PROJECT LOCATION:${NC}"
echo "   d:\wamp64\www\projects\repo-pusher\"
echo ""

echo -e "${BLUE}🌐 ACCESS URL:${NC}"
echo "   http://localhost/projects/repo-pusher/"
echo ""

echo -e "${BLUE}⚙️  SYSTEM REQUIREMENTS:${NC}"
echo "   • PHP 7.2+"
echo "   • Git 2.0+"
echo "   • WAMP/LAMP running"
echo "   • GitHub account with PAT"
echo ""

echo -e "${BLUE}🔧 FIRST-TIME SETUP:${NC}"
echo "   1. Create GitHub PAT: https://github.com/settings/tokens"
echo "   2. Go to Settings page (http://localhost/projects/repo-pusher/settings.php)"
echo "   3. Enter GitHub username"
echo "   4. Paste Personal Access Token"
echo "   5. Click 'Test Connection'"
echo "   6. Click 'Save Settings'"
echo ""

echo -e "${BLUE}📂 FILE STRUCTURE:${NC}"
echo "   config/              → Configuration files"
echo "   includes/            → PHP classes and utilities"
echo "   assets/css/          → Styling (dark mode included)"
echo "   assets/js/           → Frontend JavaScript"
echo "   actions/             → API endpoints"
echo "   logs/                → Application logs"
echo ""

echo -e "${BLUE}🚀 USAGE:${NC}"
echo "   1. Dashboard: View and search your projects"
echo "   2. Scan Projects: Detect all folders"
echo "   3. Backup: Create private GitHub repo and push code"
echo "   4. Backup All: Bulk backup all projects"
echo "   5. Settings: Configure GitHub credentials"
echo ""

echo -e "${BLUE}📝 DOCUMENTATION:${NC}"
echo "   • README.md              → Main guide"
echo "   • INSTALL.md             → Installation steps"
echo "   • API.md                 → API reference"
echo "   • TROUBLESHOOTING.md      → Problem solving"
echo "   • CONFIG_REFERENCE.md    → Configuration options"
echo ""

echo -e "${GREEN}✅ WHAT'S INCLUDED:${NC}"
echo "   ✓ Modern responsive UI with dark mode"
echo "   ✓ Project scanning and detection"
echo "   ✓ GitHub API integration"
echo "   ✓ Automatic git operations"
echo "   ✓ Single and bulk backup"
echo "   ✓ Security & validation"
echo "   ✓ Comprehensive logging"
echo "   ✓ Full documentation"
echo ""

echo -e "${YELLOW}⚠️  IMPORTANT:${NC}"
echo "   • GitHub token must start with: ghp_, ghu_, ghs_, or gho_"
echo "   • Token needs: repo + public_repo scopes"
echo "   • Never share your token!"
echo "   • Token is stored locally only"
echo "   • All repos created are PRIVATE"
echo ""

echo -e "${BLUE}🔑 CREATING GITHUB PAT:${NC}"
echo "   1. Go to https://github.com/settings/tokens"
echo "   2. Click 'Generate new token' → 'Generate new token (classic)'"
echo "   3. Name: 'GitHub Backup Manager'"
echo "   4. Expiration: 90 days (or custom)"
echo "   5. Check scopes: repo, public_repo"
echo "   6. Click 'Generate token'"
echo "   7. COPY IMMEDIATELY (only shown once!)"
echo ""

echo -e "${BLUE}🔧 TROUBLESHOOTING:${NC}"
echo "   • Git not found:        Install from https://git-scm.com"
echo "   • Token invalid:        Create new PAT, check format"
echo "   • Projects not showing: Check settings path"
echo "   • Backup fails:         Check logs/ folder for errors"
echo "   • Permissions denied:   Run WAMP as Administrator"
echo ""

echo -e "${BLUE}📊 PERFORMANCE:${NC}"
echo "   • Scan 50 projects:     2-3 seconds"
echo "   • Backup 100MB project: 8-15 seconds"
echo "   • Bulk backup 10 repos: 1-2 minutes"
echo ""

echo -e "${BLUE}🆘 COMMON COMMANDS:${NC}"
echo "   Check Git:              git --version"
echo "   Check PHP:              php --version"
echo "   View Today's Logs:      type logs\\app_*.log"
echo "   Clear Old Logs:         del logs\\app_*.log"
echo "   Test Connection:        Visit Settings, click Test Connection"
echo ""

echo -e "${BLUE}📚 API ENDPOINTS:${NC}"
echo "   GET  /actions/scan-projects.php         → List all projects"
echo "   GET  /actions/get-settings.php          → Load settings"
echo "   POST /actions/save-settings.php         → Save settings"
echo "   POST /actions/test-github.php           → Test GitHub connection"
echo "   POST /actions/backup-project.php        → Backup single project"
echo "   POST /actions/backup-all.php            → Backup all projects"
echo "   GET  /actions/get-project-details.php   → Get project info"
echo "   POST /actions/clear-data.php            → Clear all data"
echo ""

echo -e "${GREEN}🎉 YOU'RE ALL SET!${NC}"
echo ""
echo "Next steps:"
echo "  1. Start WAMP services"
echo "  2. Visit http://localhost/projects/repo-pusher/"
echo "  3. Go to Settings and configure GitHub"
echo "  4. Click 'Scan Projects' on Dashboard"
echo "  5. Click 'Backup' on any project"
echo ""

echo -e "${BLUE}Need help?${NC} See TROUBLESHOOTING.md or check logs/"
echo ""
